[package]
name = "d1"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
criterion = "0.5.1"
lazy_static = "1.4.0"
regex = "1.10.2"

[[bench]]
name = "all"
harness = false